# Generated by Django 3.0.8 on 2020-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='작성자')),
                ('contents', models.TextField(max_length=1000, verbose_name='글내용')),
                ('date', models.DateField(verbose_name='작성일')),
                ('Good', models.IntegerField(default=0)),
                ('Bad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='작성자')),
                ('contents', models.TextField(max_length=1000, verbose_name='글내용')),
            ],
        ),
    ]
