# Generated by Django 3.0.8 on 2020-08-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(verbose_name='작성일'),
        ),
    ]
