# Generated by Django 3.0.8 on 2020-08-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0002_auto_20200806_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='date',
        ),
    ]
