# Generated by Django 3.0.8 on 2020-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0003_remove_board_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default=0, max_length=20, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
