# Generated by Django 3.0.8 on 2020-08-06 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0004_board_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bd_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_bbs.Board'),
            preserve_default=False,
        ),
    ]
