# Generated by Django 3.0.8 on 2020-08-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0005_comment_bd_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bd_id',
        ),
    ]
