# Generated by Django 3.0.8 on 2020-08-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0008_auto_20200806_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bd_id',
        ),
    ]
