# Generated by Django 3.0.8 on 2020-08-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0010_comment_bd_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bd_id',
            new_name='board_id',
        ),
    ]
