# Generated by Django 3.0.8 on 2020-08-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0015_auto_20200806_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='board_id',
        ),
    ]
