# Generated by Django 3.0.8 on 2020-08-06 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0016_remove_comment_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='board_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_bbs.Board'),
            preserve_default=False,
        ),
    ]
